### ISSUE TITLE
Why the for loop on resolving pages?

### ISSUE THREAD

**Issue by flick36** [laravel-presets/inertia#4]
Hi, i'm triying to understand why do we need the for loop when resolving the page with the withVite function? have you encounter an special scenario where whe need to call a function sometimes and others where don't?

```
function withVite(pages: Record<string, any>, name: string) {
	for (const path in pages) {
		if (path.endsWith(`${name.replace('.', '/')}.vue`)) {
			return typeof pages[path] === 'function' 
				? pages[path]()
				: pages[path]
		}
	}

	throw new Error('Page not found: ' + name)
}
```

**Comment by innocenzi** [comment]
The `for` loop is to loop through `pages`, an object which keys are paths to SFCs and values are said SFCs. I can't access it just by the key (eg. `pages[name]`) because `name` will never be the full path.

I'm pretty sure values are always function but I believe I had such a case, hence the condition.
