### ISSUE TITLE
Auto import components and APIs on demand

### ISSUE THREAD

**Issue by MtDalPizzol** [laravel-presets/inertia#6]
HI, folks. What do you think of having components and APIs auto imported on demand via [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) and [unplugin-auto-import](https://github.com/antfu/unplugin-auto-import) out of the box? I got these working on my machine and it's certainly something I think most people would want on their projects.

I configured it directly on `vite.config.ts`. What do you think?

```ts
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import tailwindcss from 'tailwindcss'
import autoprefixer from 'autoprefixer'
import { defineConfig } from 'laravel-vite'
import vue from '@vitejs/plugin-vue'
import inertiaLayout from './resources/scripts/inertia/layout'

export default defineConfig({
        server: {
            port: 8080
        }
    })
    .withPlugin(AutoImport({
        imports: [
            'vue'
        ],
        dts: true,
    }))
    .withPlugin(Components({
        dirs: ['resources'],
        extensions: ['vue'],
        deep: true,
        dts: true
    }))
    .withPostCSS([tailwindcss(), autoprefixer()])
    .withPlugin(inertiaLayout)
    .withPlugin(vue)
    // .withCertificates()

```

**Comment by innocenzi** [comment]
Hey, I'm aware of that plugin from Anthony, but I'm personally not a fan of auto-importing, at least components (I understand why people can like that, but I prefer explicitly importing them, especially when I have multiple components with the same or similar names). I do see the value of having Vue's `computed`, `ref` etc available globally though.

When reading that issue I considered adding a flag, but if we're going this route, I'll have to maintain this indefinitely and will probably have to accept similar requests...

Luckily Preset is composable, so you can actually make a new one that extends it: 

```ts
import { definePreset, applyNestedPreset, installPackages, extractTemplates } from '@preset/core'

export default definePreset({
	name: 'inertia:improved',
	handler: async() => {
		await applyNestedPreset({
			preset: 'laravel-presets/inertia',
			inheritsArguments: true,
			title: 'apply main inertia preset'
		})

		await installPackages({
			for: 'node',
			install: ['unplugin-auto-import', 'unplugin-vue-components'],
			dev: true,
			title: 'install unplugins'
		})

		// Put your config in the templates
		await extractTemplates({
			title: 'use updated configuration'
		})
	},
})
```

You can scaffold a preset with `npx @preset/cli init <directory>`. Since I have not written the new docs yet, feel free to ask any question you may have 👍
